### ISSUE TITLE
Platform support request: Windows (Go)

### ISSUE THREAD

**Issue by danielchristianschroeter** [microsoft/cognitive-services-speech-sdk-go#100]
I want to use Speech SDK (https://learn.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstarts/setup-platform) in Windows for my Go application. It seems only Linux is supported at the moment for Go.
Any chance to get the Speech SDK for Go for Windows?

**Comment by danielchristianschroeter** [comment]
This does not work for Visual Studio Code. I tried to install https://dotnet.microsoft.com/en-us/download/dotnet?cid=getdotnetcorecli and executed "dotnet add package Microsoft.CognitiveServices.Speech --version 1.27.0" in the same directory where my Go code is. It shows an error "Could not find any project in...". I think nuget packages only works in Visual Studio.

**Comment by czkoko** [comment]
nuget package contains the dynamic library of all platforms, including dotnet and native.
download from [https://www.nuget.org/api/v2/package/Microsoft.CognitiveServices.Speech/1.27.0](https://www.nuget.org/api/v2/package/Microsoft.CognitiveServices.Speech/1.27.0)
Then change the filename extension to zip to decompress.
The dynamic library you need is in the following directory: `microsoft.cognitiveservices.speech.1.27.0/runtimes/win-x64/native`
include  directory: `microsoft.cognitiveservices.speech.1.27.0/build/native/include/c_api`
Set CGO_CFLAGS and CGO_LDFLAGS to build

**Comment by danielchristianschroeter** [comment]
Thanks!

Here are the complete instructions to get it work:
1. Download https://www.nuget.org/api/v2/package/Microsoft.CognitiveServices.Speech/1.27.0 rename .npkg to .zip
2. Extract content to some location e.g. D:/speechsdk

Instructions for Visual Studio Code:
1. Create .vscode/launch.json
2. Add env object to configurations block, like the following with CGO_CFLAGS, CGO_LDFLAGS and PATH:

`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {
                "CGO_CFLAGS": "-ID:/speechsdk/build/native/include/c_api",
                "CGO_LDFLAGS": "-LD:/speechsdk/runtimes/win-x64/native -lMicrosoft.CognitiveServices.Speech.core",
		"PATH": "${env:PATH};D:\\speechsdk\\runtimes\\win-x64\\native"
              },
        }
    ]
}
`

Instructions for go build within PowerShell:
$env:CGO_CFLAGS = '-ID:/speechsdk/build/native/include/c_api'
$env:CGO_LDFLAGS = '-LD:/speechsdk/runtimes/win-x64/native -lMicrosoft.CognitiveServices.Speech.core'
$env:Path += ';D:/speechsdk/runtimes/win-x64/native'
go build .

Please note, if you start the Windows binary somewhere else. Adding "D:/speechsdk/runtimes/win-x64/native" to Path variable is important. Otherwise the application will not start.

Feel free to update the documentation at https://learn.microsoft.com/de-de/azure/cognitive-services/speech-service/quickstarts/setup-platform otherwise you can close the issue.

**Comment by dargilco** [comment]
Thank you @danielchristianschroeter for the detailed instructions above, I'm sure this will be useful for other developers until we officially support it and update the public documents. Closing the issue.
