### ISSUE TITLE
Unable to run on Mac Again! 

### ISSUE THREAD

**Issue by tarun-gujjula** [microsoft/cognitive-services-speech-sdk-go#102]
Did use the solution mentioned on #72 and was working. But now again I've hit a road block. 

The following error shows up and I'm unable to resolve. What am I missing? 

`Library not loaded: @rpath/MicrosoftCognitiveServicesSpeech.framework/Versions/A/MicrosoftCognitiveServicesSpeech`
  
`Referenced from: ________`
  
`Reason: tried: '/Library/Frameworks/MicrosoftCognitiveServicesSpeech.framework/Versions/A/MicrosoftCognitiveServicesSpeech' (no such file), '/System/Library/Frameworks/MicrosoftCognitiveServicesSpeech.framework/Versions/A/MicrosoftCognitiveServicesSpeech' (no such file)`
  
 Leads of any kind, will be helpful. Thank you.

**Comment by brandom-msft** [comment]
It looks like your environment has some issues but from the shared output it's not clear what step of configuring your setup this is in.

I might suggest starting fresh with these steps to see if you can get a simple quickstart running. This one has details for macOS using go:
https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?tabs=macos%2Cterminal&pivots=programming-language-go
