### ISSUE TITLE
cannot go build

### ISSUE THREAD

**Issue by dionysia-zhang** [microsoft/cognitive-services-speech-sdk-go#114]
I am using the latest Go version：1.21.4
Ubuntu20.04 x64
I cannot build the code.

- this is what I run:

go mod init speech-recognition
go get github.com/Microsoft/cognitive-services-speech-sdk-go
go build
go run speech-recognition

- this is the guide I followed:

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-speech-to-text?tabs=windows%2Cterminal&pivots=programming-language-go

- this is my referenced sample code:

https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-recognize-speech?pivots=programming-language-go#recognize-speech-to-text-from-an-audio-file

- this is what I got:

 go run speech-recognition
./speech-recognition.go:16:28: undefined: audio.NewAudioConfigFromWavFileInput
./speech-recognition.go:22:24: undefined: speech.NewSpeechConfigFromSubscription
./speech-recognition.go:28:34: undefined: speech.NewSpeechRecognizerFromConfig
./speech-recognition.go:34:52: undefined: speech.SessionEventArgs
./speech-recognition.go:38:52: undefined: speech.SessionEventArgs
./speech-recognition.go:44:21: undefined: speech.SpeechRecognitionOutcome

Could you please tell me the reason I cannot build it? Thanks~

**Comment by Trient** [comment]
<img width="1143" alt="image" src="https://github.com/microsoft/cognitive-services-speech-sdk-go/assets/15521037/f1c3f73a-02ac-4e9d-8238-f3a465e489fc">

When can you provide the sdk on macos?

**Comment by dionysia-zhang** [comment]
I solved this problem：
https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?pivots=programming-language-go&tabs=windows%2Cubuntu%2Cdotnetcli%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi

since this "**Platform requirements**" part started with **python**, I ignored the whole part...But I found that this is what required for **Go**(UNBELIEVABLE), I did the according steps, then everything is right.

**Comment by jhakulin** [comment]
@dionysia-zhang Thanks for sharing, yes speech SDK uses native libraries even with Go.
