### ISSUE TITLE
Feature Request: Real-time diarization GO

### ISSUE THREAD

**Issue by Nico-VanHaaster** [microsoft/cognitive-services-speech-sdk-go#118]
Hello All, 

I am looking to see if there are any plans of integrating Real-time diarization into the GO DK. We are currently using Speech to Text in golang and have a need to try and get the speaker Id (Guest id etc).

Are there any plans for this feature in  GO and if so do you have an approximate ETA?

**Comment by ralph-msft** [comment]
Thanks for interest in using the Cognitive Services Speech GO SDK. We have a work item tracking the addition of this feature in our backlog. If moved into active development, we will update this GitHub issue.
F 6362088
