### ISSUE TITLE
interop_utils.go:6:11: fatal error: speechapi_c_common.h: No such file or directory

### ISSUE THREAD

**Issue by ta2swu** [microsoft/cognitive-services-speech-sdk-go#12]
### Is it compatible with windows?
I tried in Windows 10 and I am getting the following errors ( same result in Ubuntu) when I run the main.go file from the samples 

```
go1.13\src\github.com\Microsoft\cognitive-services-speech-sdk-go\common\interop_utils.go:6:11: fatal error: speechapi_c_common.h: No such file or directory
 // #include <speechapi_c_common.h>
```

**Comment by brandom-msft** [comment]
Hi @ta2swu 

Windows isn't officially supported yet, though it is a backlog candidate in our or future work.

In Ubuntu, are you setting CGO_FLAGS in your environment?

**Comment by glecaros** [comment]
Closing as this hasn't seen activity in a bit over a month. If more help is needed please feel free to reopen it.

**Comment by somenzz** [comment]
MacBook， the same error:
❯ go run main.go
# github.com/Microsoft/cognitive-services-speech-sdk-go/common
../../../go/pkg/mod/github.com/!microsoft/cognitive-services-speech-sdk-go@v1.21.0/common/error.go:10:11: fatal error: 'speechapi_c_error.h' file not found
 #include <speechapi_c_error.h>
          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
# golang.org/x/net/http2/h2c
../../../go/pkg/mod/golang.org/x/net@v0.0.0-20220531201128-c960675eff93/http2/h2c/h2c.go:159:13: undefined: io.ReadAll
../../../go/pkg/mod/golang.org/x/net@v0.0.0-20220531201128-c960675eff93/http2/h2c/h2c.go:160:11: undefined: io.NopCloser
note: module requires Go 1.17

========
❯ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOENV="/Users/aaron/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aaron/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aaron/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/aaron/github/somenzz/somenzz_rear_end/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w6/hvgxvbcj5fq45t_h5rhg_2r40000gn/T/go-build242675159=/tmp/go-build -gno-record-gcc-switches -fno-common"

Help me please, thank you!
