### ISSUE TITLE
undefined: speech.SpeechSynthesisEventArgs

### ISSUE THREAD

**Issue by dengao123** [microsoft/cognitive-services-speech-sdk-go#120]
![image](https://github.com/microsoft/cognitive-services-speech-sdk-go/assets/21308997/9ab4046d-1f17-4aa2-b19f-a5d9121669f5)

[https://learn.microsoft.com/zh-cn/azure/ai-services/speech-service/get-started-text-to-speech?tabs=linux%2Cterminal&pivots=programming-language-go](url)
When I use the example code above to tts, an error occurs

```[tasklist]
### Tasks
```

**Comment by animalnots** [comment]
got the same issue

**Comment by czkoko** [comment]
CGO_ENABLED=1

**Comment by animalnots** [comment]
> @animalnots @dengao123 CGO_ENABLED=1



> @animalnots @dengao123 CGO_ENABLED=1

set it as environment variable, didn't help

**Comment by kLkA** [comment]
Download speechsdk and setup following env vars for mac:
```
export SPEECHSDK_ROOT="$HOME/speechsdk" 
export CGO_CFLAGS="-I$SPEECHSDK_ROOT/MicrosoftCognitiveServicesSpeech.xcframework/macos-arm64_x86_64/MicrosoftCognitiveServicesSpeech.framework/Headers"
export CGO_LDFLAGS="-Wl,-rpath,$SPEECHSDK_ROOT/MicrosoftCognitiveServicesSpeech.xcframework/macos-arm64_x86_64 -F$SPEECHSDK_ROOT/MicrosoftCognitiveServicesSpeech.xcframework/macos-arm64_x86_64 -framework MicrosoftCognitiveServicesSpeech"
export LD_LIBRARY_PATH="$SPEECHSDK_ROOT/lib/arm64:$LD_LIBRARY_PATH"
```
or for linux arm64
```
export SPEECHSDK_ROOT="$HOME/speechsdk"
export  LD_LIBRARY_PATH="$SPEECHSDK_ROOT/lib/x64:$LD_LIBRARY_PATH"
export  CGO_CFLAGS="-I$SPEECHSDK_ROOT/include/c_api"
export  CGO_LDFLAGS="-L$SPEECHSDK_ROOT/lib/x64 -lMicrosoft.CognitiveServices.Speech.core"
```
```

**Comment by jBernavaPrah** [comment]
Hi to all,

Thank @kLkA, you pointed me in the right direction! :)

For how will need it, the xcframework zip for MacOS can be downloaded using this command:
`wget -O MicrosoftCognitiveServicesSpeech.xcframework.zip https://aka.ms/csspeech/macosbinary`

More info in [this example](https://github.com/Azure-Samples/cognitive-services-speech-sdk/tree/master/quickstart/cpp/macos/from-microphone).
