### ISSUE TITLE
stream model must use 1-3second to recognize 

### ISSUE THREAD

**Issue by wangzhenxing** [microsoft/cognitive-services-speech-sdk-go#13]
use too many times to recognize. is there any way to reduce it?

**Comment by wangzhenxing** [comment]
@trrwilson

**Comment by brandom-msft** [comment]
Hi @wangzhenxing, can you please provide more details about your scenario? Here are some questions that would be helpful:

How are you using the SDK?

What is behavior you are expecting?

What is the issue you are observing?

**Comment by glecaros** [comment]
Closing this thread as it hasn't had any activity in a bit over a month. Please feel free to reopen if more help is needed.
