### ISSUE TITLE
Not receiving the wordBoundary event callback

### ISSUE THREAD

**Issue by laomolaomo** [microsoft/cognitive-services-speech-sdk-go#131]
### **In the following sections 1 and 2, only the way speechConfig is created is different; all other code is the same.**

**1. Using NewSpeechConfigFromHostWithSubscription("https://southeastasia.voice.speech.microsoft.com", subscriptionKey) not receiving the wordBoundary event callback, please see the code below.**

`func` callMsSdk(req m.TTSReq, ssml string, cfg m.VoiceConfig) (ttsResp MsSdkRespData, err error) {

	speechConfig, err := speech.NewSpeechConfigFromHostWithSubscription("https://southeastasia.voice.speech.microsoft.com", cfg.MsKey)

	if err != nil {
		return
	}
	defer speechConfig.Close()

	speechConfig.SetProperty(common.SpeechServiceResponseRequestWordBoundary, "true")

	if cfg.DeploymentID != "" {
		err = speechConfig.SetProperty(common.SpeechServiceConnectionEndpointID, cfg.DeploymentID)
		if err != nil {
			return
		}
	}

	speechSynthesizer, err := speech.NewSpeechSynthesizerFromConfig(speechConfig, nil)
	if err != nil {
		return
	}
	defer speechSynthesizer.Close()

	speechSynthesizer.SynthesisStarted(func(event speech.SpeechSynthesisEventArgs) {
		defer event.Close()
		fmt.Println("SynthesisStarted")
	})

	wordList := make([]RespSdkWord, 0)
	
	if req.EnableSubtitle != nil && *req.EnableSubtitle {
		speechSynthesizer.WordBoundary(func(event speech.SpeechSynthesisWordBoundaryEventArgs) {
			defer event.Close()
			fmt.Sprintf("word boundary event, audioOffset [%d], text [%s], duration [%d]", event.AudioOffset, event.Text, event.Duration)

			wordList = append(wordList, RespSdkWord{
				AudioOffset: int64(event.AudioOffset),
				Text:        event.Text,
				Duration:    event.Duration.Milliseconds(),
			})
		})
	}

	resultFuture := speechSynthesizer.SpeakSsmlAsync(ssml)

	var result speech.SpeechSynthesisOutcome

	select {
	case result = <-resultFuture:
		defer result.Close()
		switch result.Result.Reason {
		case common.SynthesizingAudioCompleted:
			ttsResp.VoiceFile = base64.StdEncoding.EncodeToString(result.Result.AudioData)
			ttsResp.Subtitles = wordList
		case common.Canceled:
		}
	case <-time.After(time.Duration(cfg.TimeOut) * time.Millisecond):
		return
	}
	return
}

**2. Using NewSpeechConfigFromSubscription(subscriptionKey string, region string) to create SpeechConfig does receive the wordBoundary event callback, please see the code below.**

`func` callMsSdk(req m.TTSReq, ssml string, cfg m.VoiceConfig) (ttsResp MsSdkRespData, err error) {

	speechConfig, err := speech.NewSpeechConfigFromSubscription(cfg.MsKey, cfg.SpeechRegion)
	if err != nil {
		return
	}
	defer speechConfig.Close()

	speechConfig.SetProperty(common.SpeechServiceResponseRequestWordBoundary, "true")

	if cfg.DeploymentID != "" {
		err = speechConfig.SetProperty(common.SpeechServiceConnectionEndpointID, cfg.DeploymentID)
		if err != nil {
			return
		}
	}

	speechSynthesizer, err := speech.NewSpeechSynthesizerFromConfig(speechConfig, nil)
	if err != nil {
		return
	}
	defer speechSynthesizer.Close()

	speechSynthesizer.SynthesisStarted(func(event speech.SpeechSynthesisEventArgs) {
		defer event.Close()
		fmt.Println("SynthesisStarted")
	})

	wordList := make([]RespSdkWord, 0)
	
	if req.EnableSubtitle != nil && *req.EnableSubtitle {
		speechSynthesizer.WordBoundary(func(event speech.SpeechSynthesisWordBoundaryEventArgs) {
			defer event.Close()
			fmt.Sprintf("word boundary event, audioOffset [%d], text [%s], duration [%d]", event.AudioOffset, event.Text, event.Duration)

			wordList = append(wordList, RespSdkWord{
				AudioOffset: int64(event.AudioOffset),
				Text:        event.Text,
				Duration:    event.Duration.Milliseconds(),
			})
		})
	}

	resultFuture := speechSynthesizer.SpeakSsmlAsync(ssml)

	var result speech.SpeechSynthesisOutcome

	select {
	case result = <-resultFuture:
		defer result.Close()
		switch result.Result.Reason {
		case common.SynthesizingAudioCompleted:
			ttsResp.VoiceFile = base64.StdEncoding.EncodeToString(result.Result.AudioData)
			ttsResp.Subtitles = wordList
		case common.Canceled:
		}
	case <-time.After(time.Duration(cfg.TimeOut) * time.Millisecond):
		return
	}
	return
}

**3. This is the custom function return value.**
`type` MsSdkRespData struct {
	VoiceFile string        `json:"voiceFile"` 
	Subtitles []RespSdkWord `json:"subtitles"`
}

`type` RespSdkWord struct {
	// AudioOffset is the audio offset of the word boundary event, in ticks (100 nanoseconds).
	AudioOffset int64 `json:"audioOffset"`
	// Duration is the duration of the word boundary event.
	Duration int64 `json:"duration"`
	// TextOffset is the text offset.
	TextOffset uint `json:"textOffset"`
	// WordLength is the length of the word.
	WordLength uint `json:"wordLength"`
	// Text is the text.
	Text string `json:"text"`
}

**Comment by yulin-li** [comment]
Thanks for reporting this issue.

The `https` endpoint doesn't support metadata events including word boundary, viseme etc.

You need to use the websocket host, i.e.,

`NewSpeechConfigFromHostWithSubscription("wss://southeastasia.voice.speech.microsoft.com/", subscriptionKey)`
