### ISSUE TITLE
ContinuousFromMicrophone no error information

### ISSUE THREAD

**Issue by scottlance** [microsoft/cognitive-services-speech-sdk-go#16]
When running the ContinuousFromMicrophone sample, the code is failing on ` speechRecognizer, err := speech.NewSpeechRecognizerFromConfig(config, audioConfig)`

I get the following error information:
`Got an error: `  

There is no error code and I can't tell if it's a subscription setup issue (I don't think it is), or if its the `audioConfig` setup

**Comment by glecaros** [comment]
Hi @scottlance, can you try capturing a log trace? You can set it like this:
```go
config.SetProperty(common.SpeechLogFilename, "your_file_name")
```

**Comment by pankopon** [comment]
@scottlance Is this still a valid issue for you, can you please provide the log as requested?

**Comment by jhakulin** [comment]
Error is still valid, we have found a problem and making a fix.

**Comment by jhakulin** [comment]
Fix has been done, closed
