### ISSUE TITLE
Add examples for all audio stream types

### ISSUE THREAD

**Issue by adambezecny** [microsoft/cognitive-services-speech-sdk-go#22]
hi,

while audio input push streams are really easy to grasp and they are well documented by existing examples there are no samples for:

- audio input pull streams
- audio output push/pull streams

It would be really good to have some meaningful examples not only explaining how to use these streams but also explaining when to prefer pull over push (I am struggling to understand for example what is the good use case to use input pull stream instead of input push stream).

thanks!

**Comment by ralph-msft** [comment]
Thanks for using the Cognitive Speech SDK!

### Audio input pull streams:
* [Example of using a pull input stream](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_recognition_samples.cs#L416)
* [Implementing PullAudioInputStreamCallback](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs#L92)

### Audio out push streams:
* [Example of using a push output stream](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/speech_synthesis_samples.cs#L373)
* [Implementation of PushAudioOutputStreamCallback](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/samples/csharp/sharedcontent/console/helper.cs#L156)

### Audio out pull streams:
We don't have these in our SDK
