### ISSUE TITLE
Is use of goroutine needed in SpeechRecognizer.StartContinuousRecognitionAsync ?

### ISSUE THREAD

**Issue by adambezecny** [microsoft/cognitive-services-speech-sdk-go#23]
hi,

this is rather question than idea or issue. I am trying to create Rust library for MS Speech SDK (_cognitive-services-speech-sdk-rs_) by reverse engineering this Golang library. I have noticed that _StartContinuousRecognitionAsync_ function does use goroutine:

https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L165

Originally I thought this is because _recognizer_start_continuous_recognition_async_wait_for_ function will block for the whole time of recognition but by playing with it (adding sample logs around it, etc.) I found out this function will return rather quickly (e.g. for 10 second file it will take just couple of milliseconds).

**My question**: is goroutine really needed here? In my Rust code I tried implementing it in both ways, i.e. standard (non-asynchronous) and asynchronous function and both cases seem to work well (but testing so far was rather limited).

May I know about reasons that lead to design decision to make this function to utilize goroutine? Same question is probably valid for _RecognizeOnceAsync, StopContinuousRecognitionAsync, StartKeywordRecognitionAsync, StopKeywordRecognitionAsync_:

- https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L140
- https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L187
- https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L206
- https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L230

Thanks for your help!

**Comment by adambezecny** [comment]
btw. I just noticed DialogServiceConnector uses different approach when compared with SpeechRecognizer:
https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/dialog/dialog_service_connector.go#L143
vs
https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/speech/speech_recognizer.go#L206

i.e. it does not use native async function in pair with _wait_for function but rather function which seems to be sync/blocking. I do not see underlying code (and I do not have knowledge of C/C++) so I am rather guessing but this is how it looks like. In this case I understand why goroutine is used. 

Can you clarify why different approach for SpeechRecognizer is used as opposed to DialogServiceConnector? I can even see functions dialog_service_connector_start_keyword_recognition_async and dialog_service_connector_start_keyword_recognition_async_wait_for so in theory it could be implemented in a same way as SpeechRecognizer.

thanks for putting some light on this!

**Comment by ralph-msft** [comment]
Thanks for using the speech SDK!

Unfortunately, we don't officially support the use of the speech SDK C APIs (e.g. recognizer_start_continuous_recognition_async_wait_for) for use by third party developers at this time. These APIs are intended to be used internally when developing the various language projections for the SDK (e.g. C#, Go, Java, etc...). As such we do not guarantee that the APIs will remain stable, nor consistent in behaviour across releases.

With regards to your question about starting continuous recognition, the recognizers usually support being used in two modes:
- a single one off recognition ([RecognizeOnceAsync](e.g. recognizer_start_continuous_recognition_async_wait_for)). This asynchronous function will not complete until we have a recognition, or timed out on silence
- continuous recognition mode where we expect many recognitions. This is started by the call to [StartContinuousRecognitionAsync](https://docs.microsoft.com/en-us/cpp/cognitive-services/speech/speechrecognizer#startcontinuousrecognitionasync) which will complete when we have made necessary internal calls to be able to raise events from the recognizer. Please refer to the [Quick Start](https://docs.microsoft.com/azure/cognitive-services/speech-service/get-started-speech-to-text?pivots=programming-language-csharp&tabs=windowsinstall#continuous-recognition) for a more detailed description
