### ISSUE TITLE
PullAudioInputStreamCallback - pull_audio_input_stream_set_getproperty_callback sample

### ISSUE THREAD

**Issue by adambezecny** [microsoft/cognitive-services-speech-sdk-go#29]
hi,

this is brief follow-up to already closed issue 22 ((https://github.com/microsoft/cognitive-services-speech-sdk-go/issues/22))

I have reviewed C# examples provided by Ralph and these are really useful, thanks for that! One thing is though missing: example of _pull_audio_input_stream_set_getproperty_callback_. 

I am rather struggling to understand why should speech recognizer retrieve any kind of properties from callback (rather then setting them directly on _PullAudioInputStream_ instance). When I register the callback I can see recognizer is calling it with property ID 1024. When I was reviewing all possible valeus (https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.propertyid?view=azure-dotnet) I found out 1024 is not listed.

Is there an example showing proper use of this callback? What property is represented by value 1024?

**Comment by glecaros** [comment]
Hi,

The properties retrieved from the callback are related to the specific frame of audio you are writing (e.g timestamp). The properties it should ask for are `ConversationTranscribingService_DataBufferTimeStamp` and `ConversationTranscribingService_DataBufferUserId`

**Comment by adambezecny** [comment]
hi Gerardo,

makes little bit more sense now but I think there is a bug:

https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/master/audio/audio_input_stream.go#L168

you are using **_size_** param when passing into callback. Shouldn't it be rather **_id_** param?

**Comment by glecaros** [comment]
You are right, thank you for catching that!
