### ISSUE TITLE
[Feedback] The Public API is hard to use correctly

### ISSUE THREAD

**Issue by sebnyberg** [microsoft/cognitive-services-speech-sdk-go#46]
I couldn't find a good place to drop this feedback so putting it in an issue instead.

Going into this SDK, I was expecting something along the lines of:

```go
recognizer := speech.NewSpeechRecognizer(&speechRecognizerConfig{
  region: "myregion",
  key: "somekey",
})
defer func() { err := recognizer.Close() [...] }()
f, err := os.Open("path/to/file.wav")
if err != nil [...]
result, err := recognizer.RecognizeStream(f, speech.AudioFormatWAV)
if err != nil [...]
fmt.Println(result.Text)
```

However, replicating the above snippet is roughly 150LOC and involves working with channels and closing of various handles in the right order to avoid errors. 

As a Go developer, it would be preferable to have a more Go-friendly API. For example, its unusual to put concurrency in the public API (concurrency is for the consumer), there shouldn't be package names that are likely to be used by the consumer (e.g. `common`, `audio`), `io.ReadCloser` should be used to manage streams rather than sending filenames as strings (or gluing together io.Readers with bespoke streams), keep internal-use-only packages and functions private (use an `internal` folder), and more.

It seems that a layer is missing between the C-bound functions and what a consumer should use, and it is very hard to develop such a layer without knowing how the underlying C API works.

I'm happy that this SDK exists, because it's definitely better than nothing (given the limitations of the speech REST API). But I can't see an average Go developer picking this up and knowing what to do with it.

The way I use this API currently is that I completely tear down and re-create all resources on each request. This is the only way I've been able to reliably use this SDK beyond a single session.

**Comment by sebnyberg** [comment]
This post was meant as general feedback. Feel free to close it once it has been noted.

**Comment by glecaros** [comment]
Hi @sebnyberg,

First, thank you so much for your feedback, we really appreciate it! We understand that there some parts of this binding layer that are probably not idiomatic, this is a corollary of the decision we made about it being more consistent API-wise with what other projections expose. We definitely note your feedback on how difficult it is to use and we'll work on our documentation to make it easier.

As for changes to the API, that will have to wait until we are ready to release a new major version.

Again, thanks you so much for your feedback 😊
