### ISSUE TITLE
Got a cancellation event

### ISSUE THREAD

**Issue by ouhaiyun0** [microsoft/cognitive-services-speech-sdk-go#49]
I successfully compiled the sample in the SDK. But when I run the sample program with test wav files, I cannot get the recognition result. Especially "RecognizeContinuousUsingWrapper", there will be "cancellation event".
follow are outputs:

./samples $subscription en-US ../test_files/whats_the_weather_like.wav speech_recognizer:RecognizeContinuousUsingWrapper
Starting Continuous...
Got a cancellation event
^C
>>  get empty result text here, speech auto cancelled

./samples $subscription en-NG ../test_files/whats_the_weather_like.wav speech_recognizer:RecognizeOnceFromWavFile
Session Started (ID= 560bb414e9cf4f6b843eedf12971fc29 )
Session Stopped (ID= 560bb414e9cf4f6b843eedf12971fc29 )
Got a recognition!
>>  get empty result text here

os: centos7 
account: normal and subscription token was available

**Comment by glecaros** [comment]
Hi @ouhaiyun0 , for the second parameter in the call, that's the regions so en-US is not a valid value for it ([see here](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/regions#:~:text=Speech-to-Text%2C%20Text-to-Speech%2C%20and%20translation%20%20%20%20Geography,%20%20northcentralus%20%2018%20more%20rows%20))
