### ISSUE TITLE
recognizer have no 'addPhrase'

### ISSUE THREAD

**Issue by czkoko** [microsoft/cognitive-services-speech-sdk-go#50]
I wrote a recognizer project with js sdk, which can run perfectly. Now I want to rewrite it with Go sdk, but I find that some API are missing, 
such as 'addPhrase',
Will it be added in the future?

**Comment by chschrae** [comment]
Hi there,

Thanks for reaching out. Currently you are correct that it isn't supported in Go and I cannot give you a date when it will be supported, but I can confirm it is on our list of requested features.

**Comment by akshaychaturvediEST** [comment]
Is there any update regarding this issue? If not then please share how can I add custom phrases for multiple languages because I have to add a phrase in around 25 languages. Currently, I have only one solution for it I have to create a custom model for each language.
