### ISSUE TITLE
Speech recognition sample does not work using ogg/opus if filename has .opus extension

### ISSUE THREAD

**Issue by chrbsg** [microsoft/cognitive-services-speech-sdk-go#59]
The ASR sample doesn't work if the opus filename has the extension ".opus", but does work if it is something generic like ".null":

```
$ wget http://example-files.online-convert.com/audio/opus/example.opus

$ ./samples "$key" uksouth ./example.opus speech_recognizer:RecognizeOnceFromCompressedFile
Got an error:  Exception with an error code: 0x27 (SPXERR_GSTREAMER_INTERNAL_ERROR)

$ cp example.opus example.null

$ ./samples "$key" uksouth example.null speech_recognizer:RecognizeOnceFromCompressedFile
Done reading file.
Session Started (ID= 835b3abf230c4669a3454ce26a077ff1 )
Session Stopped (ID= 835b3abf230c4669a3454ce26a077ff1 )
Got a recognition!
This is a test file for the Opus opus file format with the purpose of providing an example for this file type. This is version 1.0.
```

This is on Ubuntu 20.04.4 LTS with all latest updates.

**Comment by glecaros** [comment]
Hi @chrbsg ,

Just to confirm, did you follow [the gstream setup instructions](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-codec-compressed-audio-input-streams?tabs=linux%2Cdebian&pivots=programming-language-csharp#install-gstreamer)?

If you did, can you please [capture a log](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-use-logging) and maybe attach it to the issue so we can take a look?

Thanks!

**Comment by chrbsg** [comment]
Yes, gstreamer is installed. As I said, opus works ok so long as the filename doesn't end in ".opus".

I tried to enable logging for that function of the sample app like so:

```
diff --git a/samples/recognizer/from_file.go b/samples/recognizer/from_file.go
index cf25d3d..5c192aa 100644
--- a/samples/recognizer/from_file.go
+++ b/samples/recognizer/from_file.go
@@ -11,6 +11,7 @@ import (
        "github.com/Microsoft/cognitive-services-speech-sdk-go/audio"
        "github.com/Microsoft/cognitive-services-speech-sdk-go/speech"
        "github.com/Microsoft/cognitive-services-speech-sdk-go/samples/helpers"
+       "github.com/Microsoft/cognitive-services-speech-sdk-go/common"
 )
 
 func RecognizeOnceFromWavFile(subscription string, region string, file string) {
@@ -94,6 +95,8 @@ func RecognizeOnceFromCompressedFile(subscription string, region string, file st
                fmt.Println("Got an error: ", err)
                return
        }
+       fmt.Println("SETTING LOG")
+       config.SetProperty(common.SpeechLogFilename, "/tmp/log.txt")
        defer config.Close()
        speechRecognizer, err := speech.NewSpeechRecognizerFromConfig(config, audioConfig)
        if err != nil {
```

But when I run the sample, that line is executed (it prints "SETTING LOG"), but there is no log saved anywhere. I've tried both absolute paths and relative paths.

Are you unable to reproduce the bug by running the sample against a regular ".opus" file as described above?

**Comment by glecaros** [comment]
Hey, I can't repro, when I run the sample targeting a file with the .opus extension it just works
```
./samples $SPEECH_SUBSCRIPTION_KEY $SPEECH_SUBSCRIPTION_REGION /home/glecaros/whatstheweatherlike.opus speech_recognizer:RecognizeOnceFromCompressedFile
```
(I'm using the file in the following archive)
[whatstheweatherlike.zip](https://github.com/microsoft/cognitive-services-speech-sdk-go/files/8446602/whatstheweatherlike.zip)

As for the log, I just added the `config.SetProperty(common.SpeechLogFilename, "/tmp/log.txt")` line and it worked properly so I'm a bit confused why it isn't working for you.

**Comment by chrbsg** [comment]
I found the problem - `gstreamer1.0-plugins-bad` wasn't installed. It appears that, when specifying opus filetype (`containerFormat = audio.OGGOPUS`), the sample requires `libgstopusparse.so`, which is one of the "bad" plugins. When the filetype is auto-detected (`containerFormat = audio.ANY`), then only the base/good plugins are required.

The log does get created once the required library is installed. It appears nothing is logged, and the log file not created, until after the library is initialised.

Apologies for the erroneous bug report, I didn't notice that the bad plugins were not installed. (It would be helpful if the "[Install the Speech SDK](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=dotnet%2Cwindows%2Cjre%2Cbrowser&pivots=programming-language-go)" instructions mentioned the gstreamer requirement).

**Comment by jhakulin** [comment]
@chrbsg Thanks for the feedback, I make sure we add an update to docs! Closing the issue.
