### ISSUE TITLE
Transcription race condition when ending continuous speech stream

### ISSUE THREAD

**Issue by chrbsg** [microsoft/cognitive-services-speech-sdk-go#60]
I have a test audio file of someone counting from 1 to 10. If I feed this as input to the SDK using PCM16, and then call `wrapper.stream.CloseStream()` (wrapper being the *SDKWrapper from the sample code), I found that I need to add `time.Sleep(1*time.Second)` before calling `wrapper.Close()`, otherwise the close operation terminates the operation before the transcription is received. 

If using an Opus file as input, then I need to call `time.Sleep(5 * time.Second)` to ensure that the full transcription is received.

It would be nice if these hardcoded delays weren't required, and the SDK would ensure that the outgoing audio buffers were flushed, and any potential transcription received (or not), before returning from `wrapper.Close()`. (It seems to work ok for wav files with `speech_recognizer:RecognizeOnceFromWavFile`?)

**Comment by chrbsg** [comment]
It happens with uncompressed PCM. 

In recognizer/wrapper.go:

```
func RecognizeContinuousUsingWrapper(subscription string, region string, file string) {
        /* If running this in a server, each worker thread should run something similar to this */
        wrapper, err := NewWrapper(subscription, region)
        if err != nil {
                fmt.Println("Got an error: ", err)
        }
        defer wrapper.Close()
        stop := make(chan int)
        go PumpFileContinuously(stop, file, wrapper)
        fmt.Println("Starting Continuous...")
        wrapper.StartContinuous(func(event *SDKWrapperEvent) {
                defer event.Close()
                switch event.EventType {
                case Recognized:
                        fmt.Println("Got a recognized event")
                case Recognizing:
                        fmt.Println("Got a recognizing event")
                case Cancellation:
                        fmt.Println("Got a cancellation event")
                }
        })
        <-time.After(10 * time.Second)
        stop <- 1
        fmt.Println("Stopping Continuous...")
        wrapper.StopContinuous()
        fmt.Println("Exiting...")
}
```

Note this function stops after a hardcoded 10 seconds (`time.After(10 * time.Second)`). If you remove that limit, and feed a fixed length audio file in (e.g. a sample captured from a microphone with a push-to-send button), then there is no way to tell if the SDK completed the transcription or not.

**Comment by glecaros** [comment]
Hey @chrbsg, that is actually the expected behavior for that sample... if you look at the implementation of close, it stops the recognition and closes the associated stream. If you want to ensure a full file is recognized, you would need to create the audio config with the `NewAudioConfigFromWavFileInput` function and call `StartContinuousRecognitionAsync`. At that point you would have to wait for either a session stopped event or a cancel event to signal when you are done processing the whole file.

**Comment by jhakulin** [comment]
Closed as answered, let us know if need more information,
