### ISSUE TITLE
hi when i run to_audio_data_stream.go  the erro exist

### ISSUE THREAD

**Issue by cumthxy** [microsoft/cognitive-services-speech-sdk-go#62]
`/home/xingyu/speechsdk/lib/x64/libMicrosoft.CognitiveServices.Speech.core.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/home/xingyu/speechsdk/lib/x64/libMicrosoft.CognitiveServices.Speech.core.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
collect2: error: ld returned 1 exit status`

how to solve it  thankyou

**Comment by glecaros** [comment]
Hi @cumthxy , which distro are you using?

**Comment by dargilco** [comment]
pending close, as there is no response from @cumthxy since April.

**Comment by jhakulin** [comment]
closed
