### ISSUE TITLE
MacBook， the same error: fatal error: 'speechapi_c_error.h' file not found

### ISSUE THREAD

**Issue by somenzz** [microsoft/cognitive-services-speech-sdk-go#66]
MacBook， the same error:
❯ go run main.go
# github.com/Microsoft/cognitive-services-speech-sdk-go/common
../../../go/pkg/mod/github.com/!microsoft/cognitive-services-speech-sdk-go@v1.21.0/common/error.go:10:11: fatal error: 'speechapi_c_error.h' file not found
 #include <speechapi_c_error.h>
          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
# golang.org/x/net/http2/h2c
../../../go/pkg/mod/golang.org/x/net@v0.0.0-20220531201128-c960675eff93/http2/h2c/h2c.go:159:13: undefined: io.ReadAll
../../../go/pkg/mod/golang.org/x/net@v0.0.0-20220531201128-c960675eff93/http2/h2c/h2c.go:160:11: undefined: io.NopCloser
note: module requires Go 1.17

========
❯ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/aaron/Library/Caches/go-build"
GOENV="/Users/aaron/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/aaron/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/aaron/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/aaron/github/somenzz/somenzz_rear_end/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/w6/hvgxvbcj5fq45t_h5rhg_2r40000gn/T/go-build242675159=/tmp/go-build -gno-record-gcc-switches -fno-common"

Help me please, thank you!

_Originally posted by @somenzz in https://github.com/microsoft/cognitive-services-speech-sdk-go/issues/12#issuecomment-1144928228_

**Comment by chschrae** [comment]
Hi there,

It seems there may be something missing in the setup. Can you take a look at these instructions and make sure you have followed each step? https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?tabs=dotnet%2Cwindows%2Cjre%2Cbrowser&pivots=programming-language-go

Let us know if that helps and if not, we can dive in deeper.

**Comment by czkoko** [comment]
You must download CognitiveServices nuget package first.
[https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech](https://www.nuget.org/packages/Microsoft.CognitiveServices.Speech)
then rename the package to zip, runtime and c header are in it.

mac build
CGO_CFLAGS="-I/microsoft.cognitiveservices.speech.1.22.0/build/native/include/c_api" \
CGO_LDFLAGS="-L. -lMicrosoft.CognitiveServices.Speech.core" \
CGO_ENABLED=1 \
GOARCH=amd64 \
go build -ldflags "-s -w -r=@executable_path"

**Comment by somenzz** [comment]
> 

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/29685944/171969960-673b71d8-80ce-4083-aada-a0bc51d32b94.png">

**Comment by somenzz** [comment]
Just why calling a text-to-speech API is so complicated？？？

**Comment by czkoko** [comment]
下载nuget包，里面有所有平台的动态库和头文件，Go可以直接使用，window,mac都可以编译成功，你没有设置CGO相关的

**Comment by somenzz** [comment]
> 下载nuget包，里面有所有平台的动态库和头文件，Go可以直接使用，window,mac都可以编译成功，你没有设置CGO相关的

microsoft.cognitiveservices.speech.1.22.0.nupkg，是这个么，改成 microsoft.cognitiveservices.speech.1.22.0.zip 后，解压不了：

<img width="378" alt="image" src="https://user-images.githubusercontent.com/29685944/172039514-bca45f5d-9b22-419f-a7dd-b842c49d0c0c.png">

**Comment by czkoko** [comment]
> > 下载nuget包，里面有所有平台的动态库和头文件，Go可以直接使用，window,mac都可以编译成功，你没有设置CGO相关的
> 
> microsoft.cognitiveservices.speech.1.22.0.nupkg，是这个么，改成 microsoft.cognitiveservices.speech.1.22.0.zip 后，解压不了：
> 
> <img alt="image" width="378" src="https://user-images.githubusercontent.com/29685944/172039514-bca45f5d-9b22-419f-a7dd-b842c49d0c0c.png">

使用第三方解压工具，比如keka,自带的没法解压

**Comment by somenzz** [comment]
> 



> > > 下载nuget包，里面有所有平台的动态库和头文件，Go可以直接使用，window,mac都可以编译成功，你没有设置CGO相关的
> > 
> > 
> > microsoft.cognitiveservices.speech.1.22.0.nupkg，是这个么，改成 microsoft.cognitiveservices.speech.1.22.0.zip 后，解压不了：
> > <img alt="image" width="378" src="https://user-images.githubusercontent.com/29685944/172039514-bca45f5d-9b22-419f-a7dd-b842c49d0c0c.png">
> 
> 使用第三方解压工具，比如keka,自带的没法解压

请教个问题：就定义一些错误代码，这个团队为什么要定义在 C 语言的头文件里，是不是有什么考虑，整的这么麻烦？

**Comment by somenzz** [comment]
>  谢谢  @czkoko 

<img width="932" alt="image" src="https://user-images.githubusercontent.com/29685944/172074290-1225f208-36b1-4390-a029-06178b2a859d.png">

**Comment by czkoko** [comment]
> > 谢谢  @czkoko ，但编译的时候报错：ld: library not found for -lMicrosoft.CognitiveServices.Speech.core
> 
> <img alt="image" width="932" src="https://user-images.githubusercontent.com/29685944/172074290-1225f208-36b1-4390-a029-06178b2a859d.png">

runtime 文件夹里复制 mac x64的 libMicrosoft.CognitiveServices.Speech.core.dylib 到编译目录

**Comment by somenzz** [comment]
> 

多谢大佬指点，可是依然报错：

<img width="982" alt="image" src="https://user-images.githubusercontent.com/29685944/172329097-3b902525-7f4b-42f3-af21-a7e56cf6df74.png">

**Comment by litao09h** [comment]
@czkoko 可以提供centos的镜像吗

**Comment by OarkcnWang** [comment]
> @czkoko 可以提供centos的镜像吗

https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/quickstarts/setup-platform?pivots=programming-language-go

centos的话，直接按照这个文档的说明装就好了，亲测是可以用的。
也可以按照上面的大佬给出的方法，Linux改下目标runtime也是可以用的

**Comment by aetherwu** [comment]
> executable_path

They just don't care.

**Comment by aetherwu** [comment]
> Just why calling a text-to-speech API is so complicated？？？

They just don't care.
It's so stupid.

**Comment by 9nut** [comment]
I hacked my way around this:

1. Follow the instructions for Speech SDK for C++ and create a blank project (e.g. azspeechlibs) and add the required package (i.e. `dotnet add package Microsoft.CognitiveServices.Speech`, etc.)
2. adjust CGO_CFLAGS to point to Speech SDK framework path:
  ```shell
   export CGO_CFLAGS="-I$SPEECHSDK_ROOT/MicrosoftCognitiveServicesSpeech.xcframework/macos-arm64_x86_64/MicrosoftCognitiveServicesSpeech.framework/Headers"
```
3. adjust CGO_LDFLAGS to point to the stuff included in the blank project in step 1:
```shell
export CGO_LDFLAGS="-L/path/to/azspeechlibs/bin/Release/net8.0/publish/runtimes/osx-$(uname -m)/native/ -lMicrosoft.CognitiveServices.Speech.core"
```
4. `go build` should now work.
