### ISSUE TITLE
Platform support request: Fedora Linux

### ISSUE THREAD

**Issue by msehnout** [microsoft/cognitive-services-speech-sdk-go#83]
Hello,

we are using Azure speech service at work and we'd like to try writing new services in Go instead of Python, but the Go SDK is not available for Fedora. I'm using containers to bypass the problem, but it's not as good as it could be. Is there any chance of getting those binary files built for latest Fedora?

Thanks for your response.

**Comment by daifuyang** [comment]
mac 支持

**Comment by jmy2022** [comment]
> we are using Azure speech service at work and we'd like to try writing new services in Go instead of Python, but the Go SDK is not available for Fedora. I'm using containers to bypass the problem, but it's not as good as it could be. Is there any chance of getting those binary files built for latest Fedora?

mac 如何解决？

**Comment by chschrae** [comment]
Does the python SDK work on the Fedora setup? This would be informative and narrow down whether it is a projection or a native code problem.

Theoretically, the GO SDK for linux should work with Fedora.

What is the error you are getting on Fedora and do you have an SDK log?

**Comment by msehnout** [comment]
> Does the python SDK work on the Fedora setup? This would be informative and narrow down whether it is a projection or a native code problem.
> 
> Theoretically, the GO SDK for linux should work with Fedora.
> 
> What is the error you are getting on Fedora and do you have an SDK log?

Hello,

I'm sorry, it's been so long I forgot what had been the issue when I tried to install the SDK on Fedora.

I'm pretty sure the missing support for OpenSSL > 1 is going to be an issue for any recent Linux distribution, but apart from that I don't recall the issue.

With Python, the installation is much easier, just `pip install`. I rewrote my apps in Python and it works just fine.

I think you can close the issue.

**Comment by chschrae** [comment]
Thank you. We are working on the SSL issue as well.
