### ISSUE TITLE
Platform support request: Windows

### ISSUE THREAD

**Issue by wxbool** [microsoft/cognitive-services-speech-sdk-go#87]
we were interfacing with the live streaming speech to text feature, we found that the current Golang Speech Sdk does not support the windows platform. We currently have scenarios where we are developing and running on the windows platform and would like to support them!

**Comment by chschrae** [comment]
Thanks for letting us know! I've added the request to our backlog and when/if we have time to add it, it will show up in the release notes. I'm going to close this issue to keep the list of open issues fresh.
