### ISSUE TITLE
Question: Can I auto detect language in .wav and transcript language with that language ?

### ISSUE THREAD

**Issue by jiangying000** [microsoft/cognitive-services-speech-sdk-go#91]
say I have an wav file
I want to auto detect language spoken in that file (fr, en, zh-CN), and make a STT process, get the text.

Is this possible with sdk?

**Comment by svarunan** [comment]
@jiangying000 
Try `speech.NewAutoDetectSourceLanguageConfigFromLanguages` to set the multi language conf and pass it to `speech.NewSpeechRecognizerFomAutoDetectSourceLangConfig`, then it should detect.

**Comment by jiangying000** [comment]
> @jiangying000 
> Try `speech.NewAutoDetectSourceLanguageConfigFromLanguages` to set the multi language conf and pass it to `speech.NewSpeechRecognizerFomAutoDetectSourceLangConfig`, then it should detect.

Hi, thanks for giving me this info，could you give me doc url about this function, can not find it

And seems the docs in azure website are outdated, it said golang sdk does not support this functionality .
![mmexport1677110253099.png](https://user-images.githubusercontent.com/23182033/220791064-83786c80-8ac3-41ce-b5aa-588b00668bd6.png)

**Comment by svarunan** [comment]
docs are not updated by MS team,  You can see those functions [here](https://github.com/microsoft/cognitive-services-speech-sdk-go/blob/ef57ed7196d9ada2210762db4dd97f1a15d50068/speech/auto_detect_source_language_config.go)

**Comment by jiangying000** [comment]
much thanks @svarunan , I believe this issue is resolved
